### ISSUE TITLE
Deploy server to AWS using EC2 and route 53

### ISSUE THREAD

**Issue by OliviaLiu417** [ChangePlusPlusVandy/MotherToMother#49]
- Deploy the server to AWS EC2 with https connection. This video might be helpful: https://www.youtube.com/watch?v=oHAQ3TzUTro&t=792s

**Comment by Kaleab-A** [comment]
- Created AWS  instance (Linux 2)
- Clone the git repo there
- Set up the environment variable
- Running with systemd


![Screenshot from 2023-11-26 11-11-00](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/50099796/b857b36a-8703-4670-aa19-497f8fc428a6)

![image](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/50099796/46a73dce-8708-4ca9-a8f8-afd90f36447f)

![image](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/50099796/df3ceca8-8659-41fe-895b-d64f1f6d63c6)

**Comment by Kaleab-A** [comment]
## Updates
- HTTPS setup is working now on https://mtmnodeserver.com/
- Also set daily automating of certificate update

## Couple of Concerns
- The site is blocked by Vanderbilt's firewall, I am using a VPN to access it.
- Since we don't have a production database yet, the backend on the server isn't fully functional.

**Comment by Kaleab-A** [comment]
## Updates
- HTTPS setup is working now on https://mtmnodeserver.com/
- Also set daily automating of certificate update

## Couple of Concerns
- The site is blocked by Vanderbilt's firewall, I am using a VPN to access it.
- Since we don't have a production database yet, the backend on the server isn't fully functional. 

@OliviaLiu417

**Comment by Kaleab-A** [comment]
## Updates
- Linking with DB is done with @Joey2441-spec 
- Waiting on VUIT help ticket
